version: '3.8'

networks:
  korp_network:
    driver: bridge

services:
  http-server-projeto-korp:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: http-server-projeto-korp:latest
    container_name: http-server-projeto-korp
    networks:
      - korp_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - korp_network
    depends_on:
      - http-server-projeto-korp

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - korp_network
    ports:
      - "9090:9090"
